apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realfevr-battle-arena-apis
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: staging-arena-api.realfevr.com
      http:
        paths:
          - path:
            pathType: ImplementationSpecific
            backend:
              service:
                name: realfevr-battle-arena-apis-staging
                port:
                  number: 80
    - host: stg-arena-api.realfevr.com
      http:
        paths:
          - path:
            pathType: ImplementationSpecific
            backend:
              service:
                name: realfevr-battle-arena-apis-staging
                port:
                  number: 80
