blacklisted:
  - fuck
  - pussy
  - ponzi
  - idiots
  - gay
  - porn
  - dick
  - sucks
  - masturbate
  - homossexual
  - scam
  - cock
  - fucks
  - masturbating
  - pussies
  - suck
  - whores
  - sex
  - retarded
  - bitch
  - cocksucker
  - cocksuckers
  - masturbation
  - retard
  - whore
  - motherfucker
  - motherfuckers
  - shitting
  - realfevr
  - cunt
  - motherfuck
  - asses
  - sucking
  - tits
  - ass
  - scammer
  - cunts
  - dicks
  - titties
  - asshole
  - scammers
  - bastard
  - cocks
  - pornography
  - fucker
  - shit
  - bastards
  - assholes
  - fevr
  - fucking
  - shitty
  - stupid
  - cunts
  - cum
  - fucked
  - sucker
  - idiot
  - bitches
  - cancer